# Created By: Narges kazemi

trigger:
  - master

pool:
  name: "xx"

stages:
  - stage: Frontend
    jobs:
      - job: BuildFrontEnd
        timeoutInMinutes: 500

        steps:
          # - script:
          #       whoami
          #   displayName: 'run whoam i -IKCOPool-build server'
          - script: |
              npm config rm proxy
              npm config rm http-proxy
              npm config rm https-proxy

            displayName: "clear proxy "
          # - script:
          #        npm cache clear -f
          #   displayName: 'clear cache'
          - script: npm config set strict-ssl false
            displayName: "set ssl proxy to false"
          #    - script:
          #         npm config set registry=https://xxx
          #      displayName: 'set registry'
          # - script:
          #     npm config get registry
          #   displayName: 'get registry'
          # - script:
          #     npm config ls -l
          #   displayName: 'npm config list'
          - script: npm install --force --legacy-peer-deps --loglevel verbose
            displayName: "install node-modules with log and legacy-peer parameters"

          - script: npm run build
            displayName: "on buildSrv-npm run build"
          - task: CopyFiles@2
            inputs:
              SourceFolder: C:\xx
              contents: "web.config*"
              targetFolder: $(Build.SourcesDirectory)\Build
              CleanTargetFolder: false
              OverWrite: true
            displayName: Add web.Config

          - script: md $(build.artifactstagingdirectory)\AvaFrontend
            displayName: create Frontend Artifact Directory
          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)\Build
              contents: "**"
              targetFolder: $(build.artifactstagingdirectory)\AvaFrontend
              CleanTargetFolder: true
              OverWrite: true
            displayName: Copy To TempFolder

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)\AvaFrontend
              ArtifactName: "Ava"
              publishLocation: "Container"
#=================================End Of Frontend CI=========================================
